// scripts/bench-report.mjs
//
// Renders measurement JSON as the markdown ladder report. Separate from
// bench-ingest.mjs so a rendering bug never forces a re-measurement: every
// renderer is a pure function of `results` and `meta`. The src/ imports are
// for constants, so findings quote what the app actually ships.

import '../tests/test_loader.mjs';

const interfacePool = await import('../src/tables/interface/pool.ts');
const ingestShared = await import('../src/ingest.ts');

// ---------------------------------------------------------------- reporting

export const mb = (bytes) => (bytes / 1e6).toFixed(1);

export const cell = (value, digits = 1) =>
  value === null || value === undefined ? '—' : value.toFixed(digits);

/** One row per rung. The outcome never collapses to "failed": `refused` (a
 * shape the path declines) and `crashed` (the process died) mean different
 * things, and each one's verbatim text follows the table. */
export function renderReport(results, meta) {
  const out = [];
  out.push('# Perf ladder report');
  out.push('');
  out.push('Generated by `node scripts/bench-ingest.mjs --ladder`, over the synthetic files');
  out.push('`scripts/make-perf-data.mjs` writes. **Every number here comes from synthetic data of');
  out.push('known width and known value distribution.** No real export contributed to it.');
  out.push('');
  out.push('Each rung is measured in its own child process, so a rung that exhausts memory');
  out.push('costs one row rather than the run. A rung that fails is a completed measurement.');
  out.push('');
  out.push('Throughput figures move by tens of percent between runs on the same bytes — page');
  out.push('cache state and whatever else the host is doing. Read them as an order of');
  out.push('magnitude, not as a regression gate; the outcome and ceiling columns are the');
  out.push('parts of this report that are stable.');
  out.push('');
  out.push(
    `- host: ${meta.platform} ${meta.arch}, node ${meta.node}, ${meta.cpus} cores, ${meta.totalMemGb} GB RAM`,
  );
  out.push(`- data: seed ${meta.seed}, ${meta.dir}`);
  out.push(`- run:  ${meta.when}`);
  if (meta.label) out.push(`- config: **${meta.label}**`);
  // Named, always. Two reports over the same seed and the same bytes differ
  // only in the binaries they were measured against, so a report that does not
  // say which binaries those were cannot be compared with another.
  for (const k of meta.staticCost?.kinds ?? []) {
    out.push(`- ${k.kind} parser: \`${k.wasm}\`, ${mb(k.bytes)} MB per instance`);
  }
  out.push('');
  out.push('## Results');
  out.push('');
  out.push(
    '| rung | shape | entities | file MB | header B | detected | casePlan ms | scan ms | plan ms | cube ms | cube MB | parse ms | worker ms | blit ms | final ms | peak RSS MB | MB/s | rows/s | outcome |',
  );
  out.push(
    '|---|---|---:|---:|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|',
  );
  for (const r of results) {
    const st = r.stages ?? {};
    out.push(
      `| \`${r.rung}\` | ${r.shape} | ${r.entities.toLocaleString()} | ` +
        `${r.fileBytes ? mb(r.fileBytes) : '—'} | ${r.headerBytes ? r.headerBytes.toLocaleString() : '—'} | ` +
        `${r.detected ? `${r.detected}${r.detectLineComplete === false ? '\\*' : ''}` : '—'} | ` +
        `${cell(st.casePlan)} | ${cell(st.scan)} | ${cell(st.columnPlan, 2)} | ${cell(st.cubeAlloc)} | ` +
        `${r.cubeBytes ? mb(r.cubeBytes) : '—'} | ` +
        `${cell(st.parse)} | ${cell(r.workerMs)} | ${cell(r.blitMs)} | ` +
        `${cell(st.finalize, 2)} | ${cell(r.peakRssMb)} | ` +
        `${r.mbPerSec ?? '—'} | ${r.rowsPerSec ? r.rowsPerSec.toLocaleString() : '—'} | ${r.outcome} |`,
    );
  }
  out.push('');
  out.push('`detected` is what `src/detect.ts` classify() makes of the file from its first');
  out.push('64 KiB. A `*` means the line that verdict rests on did not fit in that probe.');
  out.push("`scan ms` is the area kind's axis-discovery pass, which reads the Name column of");
  out.push('every row before any value is parsed — a cost the wide/interface path never pays.');
  out.push('`worker ms` and `blit ms` split `parse ms` along the line the APP divides it on:');
  out.push('a worker does `readWholeRows` then `parseBytes` and nothing else, and every block');
  out.push('every worker returns is blitted on the main thread. `worker ms` is therefore the');
  out.push('only part more workers can shorten, and `blit ms` + `cube ms` + `final ms` is the');
  out.push('serial fraction that sets the ceiling on any pool size.');
  out.push('`plan ms` is column-plan construction; `cube ms` is the contiguous');
  out.push('`Float32Array` of entities x 8,760 that `createAccumulator` allocates and fills');
  out.push('with NaN. The cube is measured even where the column plan is refused, because');
  out.push('its cost is a property of the width and not of whether the file is accepted.');
  out.push('');
  out.push(...renderStaticCost(meta.staticCost));
  out.push(...renderDrops(results, meta));
  out.push(...renderCeilings(results));

  out.push('## What each rung proves');
  out.push('');
  for (const r of results) out.push(`- \`${r.rung}\` — ${r.proves}`);
  out.push('');

  out.push(...renderFindings(results));

  const bad = results.filter((r) => r.outcome !== 'ok');
  out.push('## Outcomes that were not success, verbatim');
  out.push('');
  if (bad.length === 0) {
    out.push('None. Every rung completed.');
  } else {
    for (const r of bad) {
      out.push(`### \`${r.rung}\` — ${r.outcome} at \`${r.failedStage}\``);
      out.push('');
      out.push('```');
      out.push(r.error);
      out.push('```');
      out.push('');
    }
  }
  out.push(...renderBrowserProtocol(results, meta));
  return out.join('\n');
}

/** Pre-drop tab RSS, from the browser confirmation section: the low end of
 * the observed range, so "over budget" is concluded on the most generous
 * baseline. */
const BROWSER_BASELINE_BYTES = 250e6;

/** The peak-tab memory budget (1 GiB) the wide-ingest candidates are judged
 * against. */
const PEAK_TAB_BUDGET_BYTES = 1024 * 1024 * 1024;

/** The multi-case drop: what HOLDING several cases costs (N cases are N
 * cubes, whatever the parser does). */
function renderDrops(results, meta) {
  const drops = results.filter((r) => r.shape === 'drop');
  if (drops.length === 0) return [];

  const out = ['## The multi-case drop', ''];
  out.push('One Case holds several tables and a study compares runs, so dropping several');
  out.push('bus-width cases in one session is a normal thing to do. Each finalizes into one');
  out.push('contiguous `Float32Array` of entities x 8,760 that is held for as long as the');
  out.push('case is loaded. These rows are measured with every earlier case still held --');
  out.push('the tables are kept alive deliberately, so what is sampled is residency and not');
  out.push('a parse that has already been collected.');
  out.push('');

  for (const drop of drops) {
    out.push(`### \`${drop.rung}\``);
    out.push('');
    if (drop.outcome !== 'ok') {
      out.push(
        `**${drop.outcome.toUpperCase()}** at \`${drop.failedStage}\` with ` +
          `${drop.casesLoaded ?? 0} case(s) loaded. The verbatim text is below.`,
      );
      out.push('');
      continue;
    }
    out.push(
      '| cases held | cube MB | cubes held MB | RSS MB | rise over previous MB | parse ms |',
    );
    out.push('|---:|---:|---:|---:|---:|---:|');
    let previous = drop.baselineRssMb;
    drop.cases.forEach((c, i) => {
      out.push(
        `| ${i + 1} | ${c.cubeMb} | ${c.heldCubeMb} | ${c.rssMb} | ` +
          `${(c.rssMb - previous).toFixed(1)} | ${cell(c.parseMs)} |`,
      );
      previous = c.rssMb;
    });
    out.push('');
    const first = drop.cases[0];
    const marginals = drop.cases.slice(1).map((c, i) => c.rssMb - drop.cases[i].rssMb);
    const meanMarginal = marginals.reduce((a, b) => a + b, 0) / (marginals.length || 1);
    out.push(`- baseline, parser standing and nothing loaded: **${drop.baselineRssMb} MB**`);
    out.push(
      `- the FIRST case costs ${(first.rssMb - drop.baselineRssMb).toFixed(1)} MB over that, ` +
        `against a ${first.cubeMb} MB cube — about ` +
        `${(first.rssMb - drop.baselineRssMb - first.cubeMb).toFixed(0)} MB of parse working set ` +
        `(block buffers, the input window as it is touched) that is paid once and does not recur`,
    );
    out.push(
      `- every case AFTER the first costs a mean of **${meanMarginal.toFixed(1)} MB**, against a ` +
        `${first.cubeMb} MB cube. **The marginal cost of a held case is the cube and almost ` +
        `nothing else** — the presence and TOU bitmaps and the two name arrays are under 1 MB ` +
        `at this width.`,
    );
    if (drop.settledRssMb !== undefined) {
      out.push(
        `- after an explicit collection: **${drop.settledRssMb} MB**, against ${drop.peakRssMb} MB ` +
          `peak. Nothing meaningful is transient; what is held is held.`,
      );
    }
    out.push('');

    // The projection. Node has one wasm instance and no Worker, so its RSS is
    // not a tab's -- but every term that differs is measured elsewhere in this
    // report, so the sum is arithmetic over measurements rather than a guess.
    const perInstance = meta.staticCost?.perInstanceBytes ?? 0;
    const interfaceOnly =
      (meta.staticCost?.kinds ?? []).find((k) => k.kind === 'interface')?.bytes ?? 0;
    const cap = meta.staticCost?.capPoolSize ?? 0;
    const cubeBytes = first.cubeMb * 1e6;
    const transient = (first.rssMb - drop.baselineRssMb - first.cubeMb) * 1e6;
    out.push('**Projected peak for a browser tab.** Node holds one wasm instance and creates no');
    out.push("Worker, so its RSS is not a tab's. Every term that differs is measured elsewhere");
    out.push('in this report, so the sum below is arithmetic over measurements — but it is a');
    out.push('projection, and the browser confirmation is what settles it.');
    out.push('');
    out.push(
      `Terms: a ${mb(BROWSER_BASELINE_BYTES)} MB pre-drop tab; the static pool at ` +
        `\`POOL_CAP\` = ${cap}; ${first.cubeMb} MB per held case; and ` +
        `${(transient / 1e6).toFixed(0)} MB of parse working set, counted once.`,
    );
    out.push('');
    out.push(
      '| cases | cubes MB | + interface pool only | + both pools | vs the 1,024 MiB peak-tab budget |',
    );
    out.push('|---:|---:|---:|---:|---|');
    for (let n = 1; n <= drop.cases.length; n++) {
      const cubes = n * cubeBytes;
      const base = BROWSER_BASELINE_BYTES + cubes + transient;
      const oneKind = base + interfaceOnly * cap;
      const bothKinds = base + perInstance * cap;
      const verdict =
        bothKinds <= PEAK_TAB_BUDGET_BYTES
          ? 'within'
          : oneKind <= PEAK_TAB_BUDGET_BYTES
            ? '**over with both pools**'
            : '**OVER either way**';
      out.push(`| ${n} | ${mb(cubes)} | ${mb(oneKind)} | ${mb(bothKinds)} | ${verdict} |`);
    }
    out.push('');
    out.push('"Interface pool only" is a session that has dropped no Area file: `poolPromise`');
    out.push('in each `pool.ts` is per kind and lazy, so a tab that has only ever seen');
    out.push('interface tables stands up one pool. A tab that has seen both holds both, for as');
    out.push('long as it lives — neither pool has a `terminate`.');
    out.push('');
  }
  return out;
}

/** What the pools cost before any file is dropped, beside the 256 MiB static
 * budget: a cost of the BUILD, paid by every tab. */
function renderStaticCost(cost) {
  const out = ['## Static pool cost', ''];
  if (!cost) {
    out.push('Not measured in this run.');
    out.push('');
    return out;
  }
  out.push('One wasm instance per worker, fixed at instantiation, never torn down.');
  out.push('This is what the app costs an idle tab. It does not vary with the file.');
  out.push('');
  out.push('| kind | binary | per instance MB | dimensions |');
  out.push('|---|---|---:|---|');
  for (const k of cost.kinds) {
    const d = k.dimensions;
    const shape =
      k.kind === 'interface'
        ? `arena ${mb(d.arenaBytes)} MB, input window ${mb(d.inbufBytes)} MB ` +
          `(slab shape is per file, not per build)`
        : `arena ${mb(d.arenaBytes)} MB, input window ${mb(d.inbufBytes)} MB, ` +
          `area table ${d.areaTable === null ? 'unprobed' : d.areaTable.toLocaleString()}`;
    out.push(`| ${k.kind} | \`${k.wasm}\` | ${mb(k.bytes)} | ${shape} |`);
  }
  out.push('');
  const budgetMib = 256;
  const capPoolMib = cost.capPoolBytes / (1024 * 1024);
  out.push(`- both kinds, one instance each: **${mb(cost.perInstanceBytes)} MB**`);
  out.push(
    `- x ${cost.localPoolSize} workers (this host's \`poolSize()\`): ` +
      `**${mb(cost.localPoolBytes)} MB**`,
  );
  out.push(
    `- x ${cost.capPoolSize} workers (\`POOL_CAP\`, and the figure the 256 MiB static budget is judged on): ` +
      `**${mb(cost.capPoolBytes)} MB** — ${capPoolMib.toFixed(0)} MiB against a ` +
      `${budgetMib} MiB budget, **${capPoolMib <= budgetMib ? 'within' : 'OVER'}**`,
  );
  out.push('');
  out.push("The dimensions column is read from the module's own exports, not from the");
  out.push('build script — `--initial-memory` is a request and the module is what answers.');
  out.push("The area kind's table capacity has no export and is probed by filling it until");
  out.push('`area_table_put` refuses.');
  out.push('');
  return out;
}

/** Every ceiling above bus width and which binds first, as OBSERVED (bisection
 * and real allocation). A refusal naming its constant is CLEAN; a truncation,
 * wrong answer or OOM is BAD and not shippable. */
function renderCeilings(results) {
  const probe = results.find((r) => r.shape === 'head-probe');
  const cubes = results.filter((r) => r.shape === 'cube');
  if (!probe && cubes.length === 0) return [];

  const out = ['## Ceilings above bus width', ''];

  if (probe?.walls?.length) {
    const [binding] = probe.walls;
    out.push(
      `**The binding ceiling is ${binding.firstRefused.toLocaleString()} entities.** ` +
        `${binding.lastOk.toLocaleString()} plans; ${binding.firstRefused.toLocaleString()} is ` +
        `refused, because ${binding.means}.`,
    );
    out.push('');
    out.push('| wall | last width that passes | first width refused | why | message |');
    out.push('|---|---:|---:|---|---|');
    for (const w of probe.walls) {
      out.push(
        `| \`${w.id}\` | ${w.lastOk.toLocaleString()} | ${w.firstRefused.toLocaleString()} | ` +
          `${w.means} | ${w.message.replace(/^[^:]+: /, '')} |`,
      );
    }
    out.push('');
    out.push('Both counts are BISECTED, not asserted: `head-probe-wall` walks the real');
    out.push('`readCasePlan` over head bytes the real generator produced, so a change to the');
    out.push('preamble, the name width or the probe budget moves these numbers rather than');
    out.push('quietly invalidating them. The search costs no disk — the walls are decided');
    out.push('inside the first 256 KiB, so a full file at any of these widths would refuse');
    out.push('before it read its second block.');
    out.push('');
    out.push('The two walls are separate ceilings and the lower one binds. A file between');
    out.push('them has a header the probe can hold and no room for a data row after it; only');
    out.push('above the upper wall does the header line itself fail to fit. Arithmetic over');
    out.push('the header line alone gives the upper wall, which is the wrong one: the probe');
    out.push('must also hold four preamble lines and one whole data row.');
    out.push('');
  }

  if (cubes.length) {
    out.push('### What the cube would cost, at widths no file reaches');
    out.push('');
    out.push('| entities | cube MB | cube ms | peak RSS MB |');
    out.push('|---:|---:|---:|---:|');
    for (const c of cubes) {
      out.push(
        `| ${c.entities.toLocaleString()} | ${c.cubeBytes ? mb(c.cubeBytes) : '—'} | ` +
          `${cell(c.stages?.cubeAlloc)} | ${cell(c.peakRssMb)} |`,
      );
    }
    out.push('');
    out.push('Measured by allocating the array, not by multiplying: `createAccumulator` is');
    out.push('handed a plan shaped only as far as it reads one, so the cost of the WIDTH is');
    out.push('separated from whether any file of that width could be read. None of these');
    out.push('needs a file, which is the point — a full-size file at any of these widths');
    out.push('refuses in its first 256 KiB and costs a gigabyte to say so.');
    out.push('');
  }

  const at30k = cubes.find((c) => c.entities === 30000);
  if (probe?.walls?.length && at30k) {
    const [binding] = probe.walls;
    const upper = probe.walls.at(-1);
    out.push('### Would a 30,000-bus export load?');
    out.push('');
    out.push(
      `**No. The number that stops it is ${binding.firstRefused.toLocaleString()} entities — the ` +
        `wide reader's 256 KiB head probe — and 30,000 is ` +
        `${(30000 / binding.firstRefused).toFixed(1)}x past it.**`,
    );
    out.push('');
    out.push(
      `At 30,000 entities the file is refused at \`readCasePlan\` with ` +
        `"${upper.message.replace(/^[^:]+: /, '')}" — a CLEAN refusal that names the constant ` +
        `and the byte budget, on the main thread, before a Worker or a wasm instance exists.`,
    );
    out.push('');
    out.push(
      `The ${mb(at30k.cubeBytes)} MB cube is real — it is measured above, ` +
        `and it alone exceeds the whole 1,024 MiB tab budget — but it is never reached, so it ` +
        `is not what a 30,000-bus export would hit first. Raising the head probe without ` +
        `solving the cube's size would turn today's clean refusal into an out-of-memory ` +
        `kill, which is an unacceptable outcome.`,
    );
    out.push('');
    out.push('So the ceilings above bus width, in the order a widening export meets them:');
    out.push('');
    out.push('| # | ceiling | where | binds at | outcome quality |');
    out.push('|---:|---|---|---:|---|');
    out.push(
      `| 1 | head probe, header + first data row | \`HEAD_PROBE_BYTES\`, ` +
        `\`src/tables/wide/pool.ts\` | ${binding.firstRefused.toLocaleString()} | clean refusal |`,
    );
    if (probe.walls.length > 1) {
      out.push(
        `| 2 | head probe, header line alone | the same constant | ` +
          `${upper.firstRefused.toLocaleString()} | clean refusal |`,
      );
    }
    out.push(
      `| 3 | contiguous cube | \`createAccumulator\`, the same module | ` +
        `unreached (${mb(at30k.cubeBytes)} MB at 30,000) | not reached |`,
    );
    out.push('');
  }

  return out;
}

/** The ceilings as observed, derived from the results, never typed by hand. */
function renderFindings(results) {
  const out = ['## Findings', ''];
  const okAt = (shape) =>
    results.filter((r) => r.shape === shape && r.outcome === 'ok').at(-1) ?? null;
  const firstBad = (shape) => results.find((r) => r.shape === shape && r.outcome !== 'ok') ?? null;

  const wideOk = okAt('wide');
  const wideBad = firstBad('wide');
  if (wideOk && wideBad) {
    // Attributed by the refusing STAGE, since the binding ceiling moves as
    // the parser changes.
    const ceiling =
      wideBad.failedStage === 'casePlan'
        ? {
            name: 'The widest wide export that loads',
            where: 'the head probe, before the file is read',
          }
        : wideBad.failedStage === 'columnPlan'
          ? { name: 'Wide column plan', where: 'the parser layout' }
          : { name: `Wide shape, refused at \`${wideBad.failedStage}\``, where: 'that stage' };
    out.push(
      `**${ceiling.name}.** ${wideOk.entities.toLocaleString()} entities load as a full file; ` +
        `${wideBad.entities.toLocaleString()} is refused at \`${wideBad.failedStage}\` — ` +
        `${ceiling.where}. The ceiling is exact and it is a refusal, not a truncation. ` +
        `The exact count either side of it is bisected in "Ceilings above bus width" above; ` +
        `these two are the full-size files that confirm the bisection against real bytes.`,
    );
    out.push('');
  }

  const axisOk = okAt('area-axis');
  const axisBad = firstBad('area-axis');
  if (axisOk && axisBad) {
    // The same ceiling is now reachable two ways, and they do not say the same
    // thing. Worth stating together: a ceiling whose message depends on which
    // seam found it is a ceiling only half of whose users can act on it.
    const longOk = okAt('long');
    const longBad = firstBad('long');
    out.push(
      `**Area name table.** ${axisOk.entities.toLocaleString()} axis entries load; ` +
        `${axisBad.entities.toLocaleString()} is refused at \`${axisBad.failedStage}\`. ` +
        `Exact, and again a refusal.` +
        (longOk && longBad
          ? ` Now observed from a FILE as well as from the axis probe: \`${longOk.rung}\` ` +
            `(${mb(longOk.fileBytes)} MB, ${longOk.rows.toLocaleString()} rows) loads and ` +
            `\`${longBad.rung}\` is refused at \`${longBad.failedStage}\` — inside the first ` +
            `scanned block, ${cell(longBad.stages.scan)} ms into ${mb(longBad.fileBytes)} MB, so ` +
            `the refusal costs nothing like the file it refuses. The two paths word it ` +
            `differently and only the axis one names the constant and the count; see the ` +
            `verbatim outcomes below.`
          : ''),
    );
    out.push('');
  }

  // The WIDEST cube, not the last one measured: the long-shape rung comes
  // after the wide ladder and allocates a fifth of what bus width does.
  const widest = results
    .filter((r) => r.cubeBytes)
    .reduce((best, r) => (r.cubeBytes > (best?.cubeBytes ?? 0) ? r : best), null);
  if (widest) {
    out.push(
      `**Cube allocation.** One contiguous \`Float32Array\` of ` +
        `${widest.entities.toLocaleString()} x 8,760 is ${mb(widest.cubeBytes)} MB and ` +
        `allocates in ${cell(widest.stages.cubeAlloc)} ms, with the process peaking at ` +
        `${cell(widest.peakRssMb)} MB. It succeeded at every width on this host, so at bus ` +
        `width the allocation is a cost, not a wall -- on 32 GB of RAM. Whether it is a wall ` +
        `in a browser tab is the browser confirmation's question.` +
        (widest.shape === 'cube'
          ? ` Note the widest figure above comes from a PROBE, not a rung: no file of that ` +
            `width gets as far as allocating, because the head probe refuses first. What it ` +
            `measures is the cost of the width, held separate from whether the width is ` +
            `readable.`
          : ''),
    );
    out.push('');
  }

  const biggestHeader = results.reduce(
    (best, r) => (r.headerBytes > (best?.headerBytes ?? 0) ? r : best),
    null,
  );
  if (biggestHeader) {
    const budget = 256 * 1024;
    // Whether the probe is a wall is READ OFF THIS RUN, not asserted: a fixed
    // claim would go stale the moment a rung is refused by this constant.
    const refusedHere = results.filter(
      (r) => r.failedStage === 'casePlan' && /header|probe/i.test(r.error ?? ''),
    );
    const widestOk = results
      .filter((r) => r.shape === 'wide' && r.outcome === 'ok')
      .reduce((best, r) => (r.headerBytes > (best?.headerBytes ?? 0) ? r : best), null);
    const nameChars = Math.round(biggestHeader.headerBytes / biggestHeader.entities) - 1;
    out.push(
      `**Wide head probe.** ` +
        (refusedHere.length === 0
          ? `The widest header line measured is ${biggestHeader.headerBytes.toLocaleString()} B ` +
            `at ${biggestHeader.entities.toLocaleString()} entities, against the fixed ` +
            `${budget.toLocaleString()} B probe, and every rung's \`casePlan\` completed — so ` +
            `over the widths measured here it is NOT a wall, with about ` +
            `${(budget / biggestHeader.headerBytes).toFixed(1)}x headroom on the header line ` +
            `before the first data row it must also contain.`
          : `**It IS a wall, and on this ladder it is the FIRST one above bus width.** ` +
            `${refusedHere.map((r) => `\`${r.rung}\``).join(', ')} ` +
            `${refusedHere.length === 1 ? 'is' : 'are'} refused at \`casePlan\` against the ` +
            `fixed ${budget.toLocaleString()} B probe. The widest header that still plans is ` +
            `${widestOk ? `${widestOk.headerBytes.toLocaleString()} B at ${widestOk.entities.toLocaleString()} entities` : 'not in this run'}, ` +
            `which is only ` +
            `${widestOk ? (budget / widestOk.headerBytes).toFixed(1) : '?'}x headroom on the ` +
            `header LINE — and the header line is not the binding term, because the probe must ` +
            `also hold four preamble lines and one whole data row.`) +
        ` Names here are a constant ${nameChars} characters; real names longer than that would ` +
        `eat the margin, and the area parser's doubling probe would not care either way.`,
    );
    out.push('');
  }

  const truncated = results.filter((r) => r.detectLineComplete === false);
  const detected = results.filter((r) => r.detected);
  if (detected.length > 0) {
    // Judged against the rung's declared kind: wide rungs may be Generator or
    // Bus exports, routed correctly.
    const wrong = detected.filter((r) => r.detected !== r.kind);
    out.push(
      `**Detection probe — a fifth constant, not on the original list.** ` +
        `\`classify()\` is handed ${detected[0].detectProbeBytes.toLocaleString()} B. ` +
        (truncated.length === 0
          ? "Every rung's verdict line fitted inside it."
          : `At ${truncated
              .map((r) => r.entities.toLocaleString())
              .join(', ')} entities the header line the verdict rests on does NOT fit, so the ` +
            `classifier decides from a truncated line.`) +
        ` ${wrong.length === 0 ? 'Every rung was still routed to the right parser' : `${wrong.length} rung(s) were MISROUTED`}` +
        `, because the Interface branch reads line 5 for a yes/no verdict and takes the ` +
        `variant from line 1 — both survive truncation. Anything that begins using the ` +
        `columns \`classify\` parsed would have to raise this constant first.`,
    );
    out.push('');
  }

  // Candidate B priced from the split, not argued from the profile. B has since
  // landed (`POOL_CAP`), so this prices what the shipping pool gave up, and it is
  // still the figure a proposal to raise the cap back has to argue against.
  const split = results.filter((r) => r.workerMs > 0 && r.outcome === 'ok');
  if (split.length > 0) {
    const amdahl = (s, n) => 1 / (s + (1 - s) / n);
    const rows = split.map((r) => {
      const serial = r.blitMs + (r.stages.cubeAlloc ?? 0) + (r.stages.finalize ?? 0);
      const s = serial / (r.workerMs + serial);
      return { rung: r.rung, s, cost: 1 - amdahl(s, ingestShared.POOL_CAP) / amdahl(s, 8) };
    });
    out.push(
      `**The serial fraction, and what the pool cap costs.** Splitting the parse along the ` +
        `line the app divides it on -- a worker does \`readWholeRows\` then \`parseBytes\`, the ` +
        `main thread does everything else -- gives ` +
        rows.map((r) => `\`${r.rung}\` ${(r.s * 100).toFixed(1)}%`).join(', ') +
        ` serial. By Amdahl, a pool of ${ingestShared.POOL_CAP} rather than 8 workers costs ` +
        rows.map((r) => `${(r.cost * 100).toFixed(0)}%`).join(', ') +
        `. Node's main-thread blit is roughly seven times faster than a browser's, so these ` +
        `figures are the optimistic bound on the SERIAL side. This is a time cost, a trend and ` +
        `not a gate, traded against a static memory saving that is exact and linear in worker ` +
        `count: see the static pool cost above.`,
    );
    out.push('');
    out.push(
      `**A pool cannot beat the block count.** Blocks are cut at ` +
        `${(interfacePool.BLOCK_TARGET_BYTES / (1024 * 1024)).toFixed(0)} MiB, so ` +
        split.map((r) => `\`${r.rung}\` yields ${r.blocks} block(s)`).join(' and ') +
        `. A rung with fewer blocks than workers cannot use the pool it was given whatever ` +
        `the serial fraction says` +
        (() => {
          // Which rungs actually saturate is a property of THIS run's cut, so
          // it is derived rather than asserted, and the cap is read from
          // `ingest-shared.ts` rather than typed here.
          const cap = ingestShared.POOL_CAP;
          const short = split.filter((r) => r.blocks < cap).map((r) => `\`${r.rung}\``);
          return short.length === 0
            ? `. Every rung measured here yields at least ${cap} blocks, so none of them is ` +
                `block-starved at the app's pool cap.`
            : `. ${short.join(' and ')} yield${short.length === 1 ? 's' : ''} fewer than the ` +
                `app's cap of ${cap}, so ${short.length === 1 ? 'it is' : 'they are'} ` +
                `block-starved whatever the pool size; every other rung saturates.`;
        })(),
    );
    out.push('');
  }

  const wideThroughput = results.filter((r) => r.shape === 'wide' && r.mbPerSec);
  // The widest wide rung, not the first refused one: `find` returned
  // wide-513 and extrapolated a bus parse from a 43 MB file.
  const widestWide = results
    .filter((r) => r.shape === 'wide' && r.fileBytes)
    .reduce((best, r) => (r.entities > (best?.entities ?? 0) ? r : best), null);
  const longRun = results.find((r) => r.shape === 'long' && r.outcome === 'ok');
  if (wideThroughput.length > 0) {
    // Extrapolate from the WIDE rate; the long shape parses faster per byte
    // and would flatter the bus figure.
    const rate = wideThroughput.at(-1).mbPerSec;
    out.push(
      `**Throughput, and what it extrapolates to.** Wide shape: ` +
        wideThroughput
          .map((r) => `${r.entities.toLocaleString()} entities ${r.mbPerSec} MB/s`)
          .join(', ') +
        (longRun
          ? `. Long shape: ${longRun.entities} entities x ${longRun.metrics} metrics, ` +
            `${longRun.rows.toLocaleString()} rows, ${mb(longRun.fileBytes)} MB at ` +
            `${longRun.mbPerSec} MB/s and ${longRun.rowsPerSec.toLocaleString()} rows/s`
          : '') +
        `. Cost tracks BYTES rather than column count or row count over this range: the ` +
        `three shapes land within a factor of two of each other despite differing by an ` +
        `order of magnitude in both width and height.` +
        (widestWide
          ? widestWide.outcome === 'ok'
            ? ` The ${mb(widestWide.fileBytes)} MB bus-width file is MEASURED here rather than ` +
              `extrapolated: ${widestWide.stages.parse.toFixed(0)} ms at ${widestWide.mbPerSec} MB/s. ` +
              `It used ` +
              `to be a refusal, and the last extrapolation from this ladder put it at roughly ` +
              `${(widestWide.fileBytes / 1e6 / rate).toFixed(1)} s.`
            : ` At ${rate} MB/s the ${mb(widestWide.fileBytes)} MB \`${widestWide.rung}\` file ` +
              `would parse in roughly ${(widestWide.fileBytes / 1e6 / rate).toFixed(1)} s if it ` +
              `got past \`${widestWide.failedStage}\`. That extrapolation rests on ` +
              `${wideThroughput.length + (longRun ? 1 : 0)} points, and nothing about the ` +
              `parse is what stops this rung — it is refused before a block is cut.`
          : ''),
    );
    out.push('');
  }
  if (longRun) {
    const scan = longRun.stages.scan ?? 0;
    const parse = longRun.stages.parse ?? 1;
    out.push(
      `**The area kind's axis-discovery pass.** Reading the Name column of all ` +
        `${longRun.rows.toLocaleString()} rows costs ${cell(scan)} ms against ` +
        `${cell(parse)} ms for the full parse -- ${Math.round((scan / parse) * 100)}% on top, ` +
        `paid before a single value is read. The wide/interface path has no equivalent: its ` +
        `axis is the header line. Any new wide table kind that keys its axis to a column ` +
        `rather than to the header inherits this cost.`,
    );
    out.push('');
  }
  return out;
}

/**
 * The browser check this report cannot make: Workers each hold their own
 * wasm memory under a browser allocator, so a memory wall may arrive before
 * the parser ceilings above. A protocol generated from the run, with results
 * filled in by hand.
 */
function renderBrowserProtocol(results, meta) {
  // Hand-filled results are not regenerable, so an existing filled section is
  // carried across verbatim; the rest is regenerated.
  if (meta.priorBrowserSection) return meta.priorBrowserSection;

  const out = ['## Browser confirmation', ''];
  out.push('**Status: not yet performed.** Every row in the table below is still empty.');
  out.push('');
  out.push('Node measured all of the above in ONE process with ONE wasm instance and no');
  out.push('Worker. The app runs eight Workers, each with its own linear memory, under a');
  out.push('browser allocator. Two things therefore need a human, once per wall:');
  out.push('');
  out.push('1. **Does the app fail in the same place, for the same reason?** If node reports');
  out.push('   a column-count refusal and the app reports something else, this harness is not');
  out.push('   measuring the code path that ships.');
  out.push('2. **Is the per-Worker wasm memory budget reached FIRST?** This is the more');
  out.push('   important of the two. `parser/long/block.c` warns that eight Workers at their');
  out.push('   per-instance memory cost exhaust the budget before a single case completes. If');
  out.push('   the browser hits that wall earlier than the parser-constant wall above, then');
  out.push('   raising the parser constants fixes nothing.');
  out.push('');
  out.push('### How');
  out.push('');
  out.push('```bash');
  out.push('node scripts/make-perf-data.mjs --ladder --yes   # if not already generated');
  out.push('npm run dev');
  out.push('```');
  out.push('');
  out.push('Open the app with developer tools on the Memory and Console tabs. Drop **one file');
  out.push('at a time** — every wide rung carries the same quantity in its title line, so two');
  out.push('of them dropped together collide on one table-slot key and you would be measuring');
  out.push('the Import Dialog instead of the parser. Take a heap snapshot, or watch');
  out.push('`performance.memory` / the browser task manager, across the parse.');
  out.push('');
  out.push('### Walls to confirm');
  out.push('');
  const walls = results.filter((r) => r.outcome !== 'ok' && r.file !== null && r.fileBytes);
  out.push('| # | file | node outcome | app outcome | app peak memory | matches node? |');
  out.push('|---|---|---|---|---|---|');
  walls.forEach((r, i) => {
    const summary = (r.error ?? '').split('\n')[0].slice(0, 70);
    out.push(
      `| ${i + 1} | \`${meta.dir}/${r.rung}.csv\` | ${r.outcome} at \`${r.failedStage}\`: ` +
        `${summary}… | | | |`,
    );
  });
  out.push('');
  out.push('Also confirm, on the two rungs that SUCCEED in node, that they still succeed in');
  out.push('the browser and at what peak memory — a wall that only the browser has would show');
  out.push('up here and nowhere else:');
  out.push('');
  out.push('| # | file | node outcome | app outcome | app peak memory | matches node? |');
  out.push('|---|---|---|---|---|---|');
  results
    .filter((r) => r.outcome === 'ok' && r.fileBytes)
    .forEach((r, i) => {
      out.push(
        `| ${i + 1} | \`${meta.dir}/${r.rung}.csv\` | ok, ${cell(r.peakRssMb)} MB peak RSS | | | |`,
      );
    });
  out.push('');
  const fileless = results.filter((r) => r.outcome !== 'ok' && !r.fileBytes);
  if (fileless.length > 0) {
    out.push(
      `Not confirmable by hand: ${fileless
        .map((r) => `\`${r.rung}\``)
        .join(', ')}. These walls have no file to drop — the area name table is reached by ` +
        `filling the axis, and a file wide enough to do it would be tens of millions of rows. ` +
        `They stay node-only measurements until a bus or generator ingest exists to reach ` +
        `them from a real export.`,
    );
    out.push('');
  }
  out.push('### The question this section exists to answer');
  out.push('');
  out.push('> Is the per-Worker wasm memory budget reached before the parser-constant ceiling?');
  out.push('');
  out.push('_Unanswered._ Record yes or no here, with the evidence, before anyone designs the');
  out.push('bus or generator ingest on top of the numbers above.');
  out.push('');
  return out;
}
